# RuboCop configuration for TheBrain MCP Server

require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

# Style configurations
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

# Layout configurations
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Metrics configurations
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'Rakefile'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'spec/**/*'

# Naming configurations
Naming/VariableNumber:
  EnforcedStyle: snake_case

# RSpec specific configurations
RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'
